apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zt-security-compliance
  title: zt-security-compliance
  description: This lab introduces you to automated Linux security compliance through
    practical, real-world scenario management. Working across two Linux machines,
    students learn how enterprise organizations measure security health, apply automated
    fixes, manage policy exceptions, and prevent security drift on fresh deployments.  The
    lab begins on Box 1 with an initial security audit using OpenSCAP to evaluate
    an out-of-the-box system and interpret the resulting compliance report. Students
    then execute automated remediation commands to lock down the system to CIS Level
    1 (essential security) and run a follow-up scan to verify that all non-compliant
    settings pass.  To explore more advanced security models, the lab transitions
    to Box 2 to run a CIS Level 2 audit, illustrating the difference between standard
    operational hardening and maximum-security lockdown. Students then practice managing
    real-world operational exceptions by using autotailor to create custom rule overrides
    without altering vendor source files. Finally, the lab covers proactive defense
    by using Red Hat Image Builder to bake compliance profiles directly into OS blueprints,
    ensuring newly created virtual machines are secure from day one.
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: jscar-hawk
    ph.rhdp.io/owner: jloscar@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/zt-security-compliance
    ph.rhdp.io/created-at: 2026-09-15 18:33:10.916000+00:00
  tags:
  - publishing-house
  - lab
  - rhdp-published
  links:
  - url: https://github.com/rhpds/zt-security-compliance
    title: Repository
    icon: github
  - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/zt-security-compliance
    title: Open in DevSpaces
    icon: catalog
  - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
    title: Central
    icon: dashboard
  - url: https://redhat.atlassian.net/browse/RHDPCD-1649
    title: Jira Epic
    icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
